### DISCUSSION TITLE
How to represent an MPI component in the package configuration?

### DISCUSSION THREAD

**Discussion by robertsawko** [st4sd/overview#15] [Q&A] [answered]
How does ST4SD support distributed memory parallelism? I am trying to encode within the IR the following command:

```bash
mpirun -np 4 lmp_mpi < in.deck
```
I was hoping to specify just the executable `lmp_mpi` and expect ST4SD to add `mpirun` or another launcher as appropriate. I came up with the following example, but when running locally I see only a single process being spawned:

```yaml
name: RunLAMMPS
  command:
    executable: "lmp_mpi"
    arguments: "< in.deck"
  references:
    - "spec/in.deck:copy"
    - "spec/other.fs:copy"
  resourceRequest:
    numberProcesses: 4
```
I am expecting to run this on Slurm/LSF compute clusters or locally. Please advise.

**Comment by VassilisVassiliadis** [comment, marked as answer]
@robertsawko if you configure the component to use the `LSF` backend by setting

```yaml
resourceManager:
  config:
    backend: lsf
  lsf:
   queue: $the name of the queue
```

this should work as expected. ST4SD will auto-inject the `mpirun` executable (using this method: https://github.com/st4sd/st4sd-runtime-core/blob/3249d96a5a7bc9e8fd1bafe142faeca32e28fcf6/python/experiment/model/executors.py#L332-L351 to discover the location of `mpirun`)

At the moment we're ignoring `resourceRequest` for tasks that use the `local` backend.
